src/Entity/Joueur.php
<?php

namespace App\Entity;

use App\Repository\JoueurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping\PrePersist;
use Doctrine\ORM\Mapping\PreUpdate;
use Doctrine\ORM\Event\PrePersistEventArgs;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use DateTimeImmutable;
use DateTimeZone;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;

#[ORM\Entity(repositoryClass: JoueurRepository::class)]
#[HasLifecycleCallbacks]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_EMAIL', fields: ['email'])]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Joueur implements  UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(length: 50)]
    private ?string $pseudo = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date_creation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_maj = null;

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    /**
     * @var Collection<int, CompositionEquipe>
     */
    #[ORM\OneToMany(targetEntity: CompositionEquipe::class, mappedBy: 'joueur')]
    private Collection $composition;

    /**
     * @var Collection<int, Notification>
     */
    #[ORM\OneToMany(targetEntity: Notification::class, mappedBy: 'expediteur')]
    private Collection $notifs_envoyes;

    /**
     * @var Collection<int, Notification>
     */
    #[ORM\OneToMany(targetEntity: Notification::class, mappedBy: 'destinataire')]
    private Collection $notifs_recues;

    public function __construct()
    {
        $this->composition = new ArrayCollection();
        $this->notifs_envoyes = new ArrayCollection();
        $this->notifs_recues = new ArrayCollection();
    }

    #[PrePersist]
    public function setCreatedAtOnCreate(PrePersistEventArgs $eventArgs): void
    {
        $now = new DateTimeImmutable('now', new DateTimeZone('Europe/Paris'));
        $this->date_creation = $now;
        $this->date_creation = $now;
    }

    #[PreUpdate]
    public function setTimestampsOnUpdate(): void
    {
        $this->date_creation = new DateTimeImmutable('now', new DateTimeZone('Europe/Paris'));
    }

    public function __toString()
    {
        return $this->getPseudo();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): static
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeImmutable
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeImmutable $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateMaj(): ?\DateTimeInterface
    {
        return $this->date_maj;
    }

    public function setDateMaj(?\DateTimeInterface $date_maj): static
    {
        $this->date_maj = $date_maj;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection<int, CompositionEquipe>
     */
    public function getComposition(): Collection
    {
        return $this->composition;
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

    public function addComposition(CompositionEquipe $composition): static
    {
        if (!$this->composition->contains($composition)) {
            $this->composition->add($composition);
            $composition->setJoueur($this);
        }

        return $this;
    }

    public function removeComposition(CompositionEquipe $composition): static
    {
        if ($this->composition->removeElement($composition)) {
            // set the owning side to null (unless already changed)
            if ($composition->getJoueur() === $this) {
                $composition->setJoueur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifsEnvoyes(): Collection
    {
        return $this->notifs_envoyes;
    }

    public function addNotifsEnvoye(Notification $notifsEnvoye): static
    {
        if (!$this->notifs_envoyes->contains($notifsEnvoye)) {
            $this->notifs_envoyes->add($notifsEnvoye);
            $notifsEnvoye->setExpediteur($this);
        }

        return $this;
    }

    public function removeNotifsEnvoye(Notification $notifsEnvoye): static
    {
        if ($this->notifs_envoyes->removeElement($notifsEnvoye)) {
            // set the owning side to null (unless already changed)
            if ($notifsEnvoye->getExpediteur() === $this) {
                $notifsEnvoye->setExpediteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Notification>
     */
    public function getNotifsRecues(): Collection
    {
        return $this->notifs_recues;
    }

    public function addNotifsRecue(Notification $notifsRecue): static
    {
        if (!$this->notifs_recues->contains($notifsRecue)) {
            $this->notifs_recues->add($notifsRecue);
            $notifsRecue->setDestinataire($this);
        }

        return $this;
    }

    public function removeNotifsRecue(Notification $notifsRecue): static
    {
        if ($this->notifs_recues->removeElement($notifsRecue)) {
            // set the owning side to null (unless already changed)
            if ($notifsRecue->getDestinataire() === $this) {
                $notifsRecue->setDestinataire(null);
            }
        }

        return $this;
    }

}

src/Form/JoueurType.php
<?php

namespace App\Form;

use App\Entity\CompositionEquipe;
use App\Entity\Joueur;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JoueurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('pseudo')
            ->add('date_creation', null, [
                'widget' => 'single_text',
            ])
            ->add('date_maj', null, [
                'widget' => 'single_text',
            ])
            ->add('compositionEquipe', EntityType::class, [
                'class' => CompositionEquipe::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Joueur::class,
        ]);
    }
}

src/Controller/JoueurController.php
<?php

namespace App\Controller;

use App\Entity\Joueur;
use App\Form\JoueurType;
use App\Repository\JoueurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\JsonResponse;

#[Route('/joueur')]
class JoueurController extends AbstractController
{
    #[Route('/', name: 'app_joueur_index', methods: ['GET'])]
    public function index(JoueurRepository $joueurRepository): Response
    {
        return $this->render('joueur/index.html.twig', [
            'joueurs' => $joueurRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_joueur_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $joueur = new Joueur();
        $form = $this->createForm(JoueurType::class, $joueur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($joueur);
            $entityManager->flush();

            return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('joueur/new.html.twig', [
            'joueur' => $joueur,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_joueur_show', methods: ['GET'])]
    public function show(Joueur $joueur): Response
    {
        return $this->render('joueur/show.html.twig', [
            'joueur' => $joueur,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_joueur_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Joueur $joueur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(JoueurType::class, $joueur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_joueur_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('joueur/edit.html.twig', [
            'joueur' => $joueur,
            'form' => $form,
        ]);
    }

    #[Route('/chercher', name: 'app_joueur_chercher', methods: ['GET', 'POST'])]
    public function chercheJoueurs(Request $request,Security $security,EntityManagerInterface $entityManager){
        $jsonData = $request->getContent();
        $data = json_decode($jsonData, true);
        $lst_joueurs = $data['lst_joueurs'];
        $pseudo = $data['lib_joueur'];
        $repository = $entityManager->getRepository(Joueur::class);
        
        $queryBuilder = $repository->createQueryBuilder('j')
            ->where('j.pseudo LIKE :pseudo')
            ->andWhere('j.id NOT IN (:lst_joueurs)')
            ->setParameter('pseudo', "%$pseudo%")
            ->setParameter('lst_joueurs', $lst_joueurs);

        $requete = $queryBuilder->getQuery();
        $joueurs = $requete->getResult();
        $formattedJoueurs = [];
        foreach ($joueurs as $joueur) {
            $formattedJoueurs[] = [
                'id' => $joueur->getId(),
                'pseudo' => $joueur->getPseudo(),
            ];
        }
        return new JsonResponse(["data"=>$formattedJoueurs]);
    }
}

templates/joueur/_delete_form.html.twig
<form method="post" action="{{ path('app_joueur_delete', {'id': joueur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ joueur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/joueur/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/joueur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Joueur{% endblock %}

{% block body %}
    <h1>Edit Joueur</h1>

    {{ include('joueur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_joueur_index') }}">back to list</a>

    {{ include('joueur/_delete_form.html.twig') }}
{% endblock %}

templates/joueur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Joueur index{% endblock %}

{% block body %}
    <h1>Joueur index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Pseudo</th>
                <th>Date_creation</th>
                <th>Date_maj</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for joueur in joueurs %}
            <tr>
                <td>{{ joueur.id }}</td>
                <td>{{ joueur.nom }}</td>
                <td>{{ joueur.prenom }}</td>
                <td>{{ joueur.pseudo }}</td>
                <td>{{ joueur.dateCreation ? joueur.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ joueur.dateMaj ? joueur.dateMaj|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_joueur_show', {'id': joueur.id}) }}">show</a>
                    <a href="{{ path('app_joueur_edit', {'id': joueur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_joueur_new') }}">Create new</a>
{% endblock %}

templates/joueur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Joueur{% endblock %}

{% block body %}
    <h1>Create new Joueur</h1>

    {{ include('joueur/_form.html.twig') }}

    <a href="{{ path('app_joueur_index') }}">back to list</a>
{% endblock %}

templates/joueur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Joueur{% endblock %}

{% block body %}
    <h1>Joueur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ joueur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ joueur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ joueur.prenom }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ joueur.pseudo }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ joueur.dateCreation ? joueur.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_maj</th>
                <td>{{ joueur.dateMaj ? joueur.dateMaj|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_joueur_index') }}">back to list</a>

    <a href="{{ path('app_joueur_edit', {'id': joueur.id}) }}">edit</a>

    {{ include('joueur/_delete_form.html.twig') }}
{% endblock %}